version: '3'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ecommerce
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  k6:
    image: loadimpact/k6
    volumes:
      - ./scripts:/scripts
    command: run /scripts/loadtest.js

volumes:
  postgres-data:
