apiVersion: container.cnrm.cloud.google.com/v1beta1
kind: ContainerCluster
metadata:
  name: devops-demo-cluster
  namespace: gcp-project
spec:
  location: us-central1
  initialNodeCount: 3
  nodeConfig:
    machineType: e2-medium
