apiVersion: v1
kind: Service
metadata:
  name: devops-pipeline-demo-prod-service
  labels:
    app: devops-pipeline-demo
    environment: prod
spec:
  type: LoadBalancer
  selector:
    app: devops-pipeline-demo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
