apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-demo-local
  labels:
    app: devops-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devops-demo
  template:
    metadata:
      labels:
        app: devops-demo
    spec:
      containers:
      - name: devops-demo
        image: gcr.io/your-gcp-project-id/devops-demo:dev-latest
        ports:
        - containerPort: 8080
