apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-demo-local
  namespace: devops-demo
  labels:
    app: devops-demo
spec:
  ServiceAccountName: jenkins-sa
  replicas: 2
  selector:
    matchLabels:
      app: devops-demo
  template:
    metadata:
      labels:
        app: devops-demo
    spec:
      containers:
      - name: devops-demo
        image: 127.0.0.1:5000/devops-demo:dev-latest
        ports:
        - containerPort: 8080