apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins-sa
  namespace: devops-demo
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: jenkins-role
  namespace: devops-demo
rules:
- apiGroups: [""]
  resources: ["pods", "pods/logs", "services", "deployments", "configmaps", "secrets"]
  verbs: ["get", "list", "watch", "create", "delete", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins-role-binding
  namespace: devops-demo
subjects:
- kind: ServiceAccount
  name: jenkins-sa
  namespace: devops-demo
roleRef:
  kind: Role
  name: jenkins-role
  apiGroup: rbac.authorization.k8s.io
