apiVersion: v1
kind: Service
metadata:
  name: devops-demo-local
  namespace: devops-demo
  labels:
    app: devops-demo
spec:
  selector:
    app: devops-demo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort
