apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-demo-staging
  labels:
    app: devops-demo
    environment: staging
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devops-demo
      environment: staging
  template:
    metadata:
      labels:
        app: devops-demo
        environment: staging
    spec:
      containers:
      - name: devops-demo
        image: gcr.io/$PROJECT_ID/devops-demo:staging-${env.BUILD_ID}
        ports:
        - containerPort: 8080
