apiVersion: v1
kind: Service
metadata:
  name: devops-demo-staging
  labels:
    app: devops-demo
    environment: staging
spec:
  selector:
    app: devops-demo
    environment: staging
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
