apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devops-demo-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/shirocola/devops-pipeline-demo.git'
    targetRevision: prod
    path: k8s/prod
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
