apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devops-demo-staging
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/your-repo/devops-pipeline-demo.git'
    targetRevision: staging
    path: k8s/staging
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
