apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devops-demo-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/your-repo/devops-pipeline-demo.git'
    targetRevision: dev
    path: k8s/dev
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
