name: CI Workflow

on:
  push:
    branches:
      - dev
      - staging
      - prod

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Build with Maven
      run: mvn clean install

    - name: SonarQube Scan
      env:
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: mvn sonar:sonar

    - name: Trivy Scan
      run: |
        docker run --rm -v $(pwd):/app aquasec/trivy:latest --exit-code 1 --severity HIGH,CRITICAL --ignore-unfixed /app

  deploy:
    name: Deploy with Jenkins
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Trigger Jenkins Job
      uses: appleboy/jenkins-action@master
      with:
        url: ${{ secrets.JENKINS_URL }}
        username: ${{ secrets.JENKINS_USER }}
        token: ${{ secrets.JENKINS_TOKEN }}
        job: 'your-jenkins-job-name'
